[pytest]
# Directorio raíz de tests
testpaths = steps

# Opciones por defecto
addopts =
    -v
    --tb=short
    --alluredir=allure-results
    --clean-alluredir

# Configuración de pytest-bdd
bdd_features_base_dir = features
